<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Erdmier.DomainCore</RootNamespace>
        <PackageId>Erdmier.DomainCore</PackageId>
        <Title>DomainCore</Title>
        <PackageTags>domain-driven-design objects; ddd objects; erdmier; justinian</PackageTags>
        <Description>A small library for easily and quickly modeling your domain layer following DDD principles.</Description>
        <Summary>A small library for easily and quickly modeling your domain layer following DDD principles.</Summary>
        <PackageTags>domain-driven-design objects; ddd objects; justinian; erdmier</PackageTags>
        <Version>1.1.2-preview.3</Version>
        <PackageReleaseNotes>Setting up CI/CD pipelines.</PackageReleaseNotes>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
        <DefineConstants>TRACE;DEBUG</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Properties\PublishProfiles\" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>

        <None Include="..\..\LICENSE.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <!--        <None Include="$(SolutionDir)img\icon.png" Pack="true" Visible="false" PackagePath="" />-->
    </ItemGroup>

</Project>
