<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Erdmier.DomainCore.Tests.Models</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Source\DomainCore\DomainCore.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Models\" />
    </ItemGroup>

</Project>
