<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Erdmier.DomainCore.MediatorCore</RootNamespace>
        <PackageId>Erdmier.DomainCore.Mediator</PackageId>
        <Title>DomainCore.Mediator</Title>
        <Description>A small library for integrating the Erdmier.DomainCore library with the Mediator library by Martin Othamar.</Description>
        <Summary>A small library for integrating the Erdmier.DomainCore library with the Mediator library by Martin Othamar.</Summary>
        <PackageTags>domain-driven-design objects; ddd objects; justinian; erdmier; meditor</PackageTags>
        <Version>1.0.1</Version>
        <PackageReleaseNotes>Added documentation to types and members.</PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Erdmier.DomainCore" Version="2.0.0" />
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
        <PackageReference Include="Mediator.Abstractions" Version="2.1.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
    </ItemGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
        <DefineConstants>TRACE;DEBUG</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Properties\PublishProfiles\" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>

        <None Include="..\..\LICENSE.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <!--        <None Include="$(SolutionDir)img\icon.png" Pack="true" Visible="false" PackagePath="" />-->
    </ItemGroup>

</Project>
