<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Erdmier.DomainCore.MediatorCore</RootNamespace>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>Erdmier.DomainCore.MediatorCore</PackageId>
        <Version>1.0.0-preview.1</Version>
        <Title>DomainCore.Mediator</Title>
        <Authors>JustinianErdmier</Authors>
        <Description>A small library for integrating the Erdmier.DomainCore library with the Mediator library by Martin Othamar.</Description>
        <Copyright>Copyright (c) Justin Erdmier 2025.</Copyright>
        <PackageProjectUrl>https://github.com/JustinErdmier/Erdmier.DomainCore</PackageProjectUrl>
        <RepositoryUrl>https://github.com/JustinErdmier/Erdmier.DomainCore</RepositoryUrl>
        <PackageTags>domain-driven-design objects; ddd objects; meditor</PackageTags>
        <PackageReleaseNotes>Changing name of namespace. Suspected issue of namespace conflict with the Mediator library's source generation.</PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Erdmier.DomainCore" Version="1.1.1" />
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
        <PackageReference Include="Mediator.Abstractions" Version="2.1.7" />
    </ItemGroup>

</Project>
